### ISSUE TITLE
Short sample error - Unexpected identifier

### ISSUE THREAD

**Issue by chrisvella** [catcher-in-the-try/botbuilder-qna-maker#1]
The short sample fails with the following error on the 8th line:

```
const answer = await qna.answer('Hi!');
                     ^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Apologies if this is a stupid user error on my part.

Cheers

**Comment by chrisvella** [comment]
Hi @catcher-in-the-try thanks for the quick reply.

I upgraded my version of node (which was old) and got the following error with the same example code:

```
const answer = await qna.answer('Hi!');
               ^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

I then updated the sample code based on your reply:
```
//const answer = await qna.answer('Hi!');

let bot = new builder.UniversalBot(connector, async (session) => {
  session.send(await qna.answer('Hi!'));
});
```
and got this error:

```
let bot = new builder.UniversalBot(connector, async (session) => {
          ^

ReferenceError: builder is not defined
    at Object.<anonymous> (/var/www/node/vodabot/app3.js:10:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

Thanks

Edit: Updated with correct error.
